# Generated by Django 6.0.2 on 2026-04-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status_choices',
            new_name='status',
        ),
    ]
